### ISSUE TITLE
Fix compilation error in test_update_hash_indexes.rs

### ISSUE THREAD

**Issue by rjwalters** [rjwalters/nistmemsql#804]
## Bug Description

The integration test `test_update_hash_indexes.rs` fails to compile due to `TableSchema` constructor changes introduced in PR #801.

## Error

```
error: cannot construct `TableSchema` with struct literal syntax due to private fields
  --> tests/test_update_hash_indexes.rs:14:18
   |
14 |     let schema = TableSchema {
   |                  ^^^^^^^^^^^
   |
   = note: ...and other private field `column_index_cache` that was not provided
```

## Root Cause

PR #801 (Optimize SELECT WHERE performance) added a private field `column_index_cache` to `TableSchema` but did not update the test fixture in `test_update_hash_indexes.rs` which uses struct literal syntax.

## Impact

- CI fails for all PRs on main branch
- Blocks merging of PRs with passing tests (like PR #802)
- Main branch is currently broken

## Fix Required

Update `test_update_hash_indexes.rs:14` to use one of the associated constructor functions instead of struct literal syntax:
- `TableSchema::new(name, columns)`
- `TableSchema::with_primary_key(name, columns, pk)`
- `TableSchema::with_unique_constraints(name, columns, unique)`
- Or other appropriate constructor based on test needs

## Reproduction

```bash
cargo test --test test_update_hash_indexes
```

## Discovered

While reviewing PR #802 as Judge - the CI failure is unrelated to the COMMENT feature implementation.
